const data = {
    defaultProps: {
        id: "64d605cc7f04b318e",
        name: "Kara Dionisio",
        deleted: false,
        salutationName: "Dr.",
        firstName: "Kara",
        lastName: "Dionisio",
        description: null,
        emailAddress: null,
        phoneNumber: null,
        addressStreet: null,
        addressCity: null,
        addressState: null,
        addressCountry: null,
        addressPostalCode: null,
        createdAt: "2023-08-11 09:56:28",
        modifiedAt: "2023-08-11 09:56:41",
        briefBiography: "Dr. Kara Dioniso is a leader in the field of menopause practice and she is regularly invited to speak to naturopathic doctors across North America. Dr. Kara Dionisio is a NAMS-certified menopause practitioner since 2020 and holds an IMPART Menopause Certificate and a level 1 training in Pelvic Floor Physiotherapy.",
        gender: null,
        acceptingPatientsOutOfProvince: false,
        retired: false,
        disciplinaryAction: false,
        acceptingNewPatients: false,
        practiceProvinces: [],
        rate: 4,
        requirementsImagingTestingConsultation: null,
        requirementsImagingTestingReferral: null,
        requiresOwnReferralForm: false,
        contractedWithSanoliving: false,
        middleName: null,
        emailAddressIsOptedOut: null,
        emailAddressIsInvalid: null,
        phoneNumberIsOptedOut: null,
        phoneNumberIsInvalid: null,
        emailAddressData: [],
        phoneNumberData: [],
        createdById: "644be585f01a36413",
        createdByName: "Admin",
        modifiedById: "644be585f01a36413",
        modifiedByName: "Admin",
        assignedUserId: null,
        assignedUserName: null,
        teamsIds: [],
        teamsNames: {},
        biographyId: null,
        biographyName: null
    },
    additionalData: {}
}